-- Expansão gamer da campanha: XP, patente, moedas, combo, conquistas e estatísticas de campanha.
ALTER TABLE public.tribunal_progresso
  ADD COLUMN IF NOT EXISTS xp INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS conhecimento INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS moedas INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS combo INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS combo_maximo INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS medalhas INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missoes_concluidas INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS melhor_nota INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS melhor_nota_avancada INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS campanha_concluida BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS conquistas JSONB NOT NULL DEFAULT '[]'::jsonb;
